name: Setup Bun
description: Setup Bun for Node.js

inputs:
  working-directory:
    description: The working directory to install dependencies in
    required: true
    default: '.'

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.working-directory }}/bun.lock
          ${{ inputs.working-directory }}/node_modules
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      run: bun i
      shell: bash
